import { Inter } from "next/font/google";
import "./globals.css";
import Homepage from "./Homepage/page";
import Foot from "./Foot/page";
import Frontend from "./Frontend/page";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Homepage />
        {children}
        <Foot />
      </body>
    </html>
  );
}
